name: Test

on:
  push:
    branches:
      - main
      - 'releases/**'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: Code format, lint, unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Code Formatter
        run: npm run format

      - name: Lint Test
        run: npm run lint

      - name: Unit Test
        run: npm run test
